# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0002_auto_20170120_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradas',
            old_name='typeEntrada',
            new_name='tipoEntrada',
        ),
    ]
