# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0003_auto_20170120_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantante',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
