# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0004_cantante_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantante',
            name='enable',
        ),
        migrations.AddField(
            model_name='evento',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
