# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0005_auto_20170121_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='listCompra',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.Compra'),
        ),
    ]
