# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0006_auto_20170121_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantante',
            name='fechaModif',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='disco',
            name='fechaModif',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='fechaModif',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='video',
            name='fechaModif',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
