# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0007_auto_20170121_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='buyUser',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.PerfilUser'),
        ),
        migrations.AlterField(
            model_name='cantante',
            name='listDiscos',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.Disco'),
        ),
        migrations.AlterField(
            model_name='cantante',
            name='listImagenes',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.Galeria'),
        ),
        migrations.AlterField(
            model_name='cantante',
            name='listVideos',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.Video'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='listCanciones',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.Cancion'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='listEntradas',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.Entradas'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='listVideos',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.Video'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='listcantantes',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.Cantante'),
        ),
    ]
