# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0008_auto_20170121_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipoEvento',
            field=models.CharField(choices=[('festival', 'Festival'), ('concierto', 'Concierto'), ('funcion-Teatro', 'funcion-Teatro')], default='Festival', max_length=20),
        ),
    ]
