# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0009_evento_tipoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='numEntradas',
            field=models.IntegerField(default=0),
        ),
    ]
