# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0010_entradas_numentradas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantante',
            name='fechaModif',
            field=models.DateTimeField(default=datetime.date(2017, 1, 21)),
        ),
        migrations.AlterField(
            model_name='disco',
            name='fechaModif',
            field=models.DateTimeField(default=datetime.date(2017, 1, 21)),
        ),
        migrations.AlterField(
            model_name='video',
            name='fechaModif',
            field=models.DateTimeField(default=datetime.date(2017, 1, 21)),
        ),
    ]
