# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0011_auto_20170121_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantante',
            name='fechaModif',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fechaModif',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='fechaModif',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
