# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0012_auto_20170121_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='fechaModif',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
