# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0013_auto_20170121_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='perfilImg',
            field=models.ImageField(blank=True, null=True, upload_to='img_perfil/'),
        ),
    ]
