# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0014_auto_20170207_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='perfilImg',
            field=models.ImageField(blank=True, default='perfilFault.jpeg', null=True, upload_to='img_perfil/'),
        ),
    ]
