# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0015_auto_20170211_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
