# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebMultimedia', '0020_auto_20170328_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='WebMultimedia.Order')),
                ('producto', models.ManyToManyField(blank=True, to='WebMultimedia.Evento')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
