# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0021_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebMultimedia.Order'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='producto',
            field=models.ManyToManyField(blank=True, null=True, to='WebMultimedia.Evento'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
