# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0023_auto_20170416_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='listVideos',
        ),
        migrations.AddField(
            model_name='cantante',
            name='instagram',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cantante',
            name='twitter',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cantante',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
