# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMultimedia', '0024_auto_20170416_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='buyUser',
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='listCompra',
            field=models.ManyToManyField(blank=True, to='WebMultimedia.orderItems'),
        ),
    ]
